面接日程の承認/却下機能の追加
shoynoi/e-navigator pull request #3
Opened 2018-10-26 01:06 UTC by shoynoi

後半第2章の課題が完了しました。

やりたかったこと
---
- ユーザーが他のユーザーの面接日程を承認/却下する機能の追加

やったこと
----
- app/views/interviews/index.html.erb内で自身と他のユーザーで面接日程の表示を分けるパーシャルを作成
- interviews#approveを追加、面接日程を承認/他の日程を却下する機能を作成
- 面接希望日が承認/却下された場合、その日程の編集/削除リンクを無効にする
- scheduleを表示するフォーマットをinterview.rbに定義し_interviews_others.html.erbで承認された面接日時を表示

動作確認方法
---
- [ ] ユーザーを2人作成、一方で有効な面接希望日を登録しログアウト、もう一方でログインするとユーザー一覧ページに自身以外のユーザーが表示されており、面接一覧ボタンが表示される。
- [ ] 面接一覧ボタンを押下すると、ユーザーの面接希望日一覧が表示
- [ ] 有効な希望日の承認するボタンを押下すると、希望日が承認され、"面接希望日時を承認しました"とflashが表示
- [ ] すでに過ぎてしまっている日時を承認すると、"過去の日付は承認できません"をエラーが表示
- [ ] 現在承認されている面接日時面接希望一覧ページに表示

レビューよろしくおねがいします。:bow:

2018-10-29 02:37 UTC, pokotyamu commented
👀

2018-10-29 02:50 UTC, pokotyamu requested changes
@shoynoi いくつかコメントしました！適宜修正とコメント返信していただきたいです！

2018-10-29 02:50 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +      redirect_to user_interviews_path(@user)
豆知識
`redirect_to` はオプションとして `flash` の情報扱えるので、一行で書くことができますよ〜
https://qiita.com/kanpe777/items/c5154b58c852855deefc#%E5%9F%BA%E6%9C%AC

2018-10-29 02:50 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +        interview.update_attribute(:status, "rejected")
ここも `update_attribute` 使ってるんですね。
どちらかに統一されている方が良さそう

2018-10-29 02:50 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +        interview.update_attribute(:status, "rejected")
そしてせっかく `enum` を使っているのであれば、ヘルパーメソッド使うのが良いと思いました 🙋‍♂️ 

```
interview.approved?
#=> approved なら true
interview.approved!
#=> approved の状態にする
user.interviews.approved
#=> approved な面接だけのリストを作る
```

こんな感じで便利なヘルパーが追加されるので、ぜひ使ってみると良いと思いました！

2018-10-29 02:50 UTC, pokotyamu commented on app/helpers/interviews_helper.rb
> +    interview.user_id == current_user.id && interview.status != 'pending'
うーん。
ここは口頭で補足したい感じあるなぁ。
`current_user.id` の判定が `confirmed?` の中にあるのはだいぶ違和感ありますね 😓

2018-10-29 02:50 UTC, pokotyamu commented on config/routes.rb
> +        patch :approve
ちなみに、HTTP メソッドを patch メソッドとした理由ってありますか？

2018-10-29 02:55 UTC, pokotyamu commented
承認周りの動作に関しては問題ないと思いました 🆗

2018-11-05 00:47 UTC, shoynoi commented on app/controllers/interviews_controller.rb
> +        interview.update_attribute(:status, "rejected")
`enum`について調べている中でこれらのヘルパーメソッドについても知っていたのですが、うまく機能させることができませんでした。
このヘルパーでは更新時に`update!`を呼び出しているようですので、過去の日付(正常な日程の登録後、その日時が過ぎた日程)を承認するとバリデーションエラーが発生してしまいます。また、他の日程をrejectedとする場合も同様のエラーが発生してしまいます。

正常な日付をapprovedとする場合にはバリデーションの検証をさせて、それ以外の日付は過去/未来に関わらずrejectedとしたいのですが、ヘルパーメソッドを利用する方法ですとbeginやrescue等で例外を捕捉する形にするほうが良いでしょうか。

2018-11-05 00:51 UTC, shoynoi commented on config/routes.rb
> +        patch :approve
こちらはpostにすべきか迷ったのですが、すでに存在するリソースの一部を更新するアクションですので、patchとしました。

2018-11-05 00:53 UTC, shoynoi commented on app/controllers/interviews_controller.rb
> +      redirect_to user_interviews_path(@user)
参考になりました。ありがとうございます！
一行で書くように修正しました。

2018-11-05 02:06 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +        interview.update_attribute(:status, "rejected")
あーなるほどですね。
選択肢はいろいろあるのですが、

- `User` モデル側のバリデーションを、日付が変わった時だけ実行するようにする。
- `update_all` を使ってバリデーションを通さずに保存しちゃう

が考えるかなぁ。
`approved` な状態が各 `User` 毎に 1つしか作らないなら、後者の `update_all` を使って `approved` な面接以外を `rejected` にしてあげるのが一番手っ取り早くて良さそうに思いました！

2018-11-05 02:08 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +        interview.update_attribute(:status, "rejected")
ここは修正漏れかな？ 👀

2018-11-05 02:10 UTC, pokotyamu commented on config/routes.rb
> +        patch :approve
> postにすべきか迷った

うーん 🤔 
迷うべきは、 `PUT` だと思いますね。

`POST`: リソースを作成する(まるごと作る)アクション
`PUT`: リソースを全部更新するアクション
`PATCH`: リソースを一部を更新するアクション

こんな違いで使い分けるといいと思います 👍 
なので、ここで `PATCH` をつかっているのは良いと思いました 👍

2018-11-06 05:59 UTC, shoynoi commented on app/controllers/interviews_controller.rb
> +        interview.update_attribute(:status, "rejected")
`update_all`を使用したところ、より簡潔に`rejected`とする処理を記述できました。

2018-11-06 06:04 UTC, shoynoi commented on app/controllers/interviews_controller.rb
> +        interview.update_attribute(:status, "rejected")
こちらは前にコメントした時と同じ様に`enum`のヘルパーメソッドをうまく使えなかったのと、バリデーションを通さないようにするために`update_attribute`を使用していました。今回、バリデーションを通さずに一括で更新できるように`update_all`を使用するように修正しました。わかりずらくなり申し訳ありません。

2018-11-07 07:34 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +        interview.update_attribute(:status, "rejected")
`update_attributes` と見間違いしてた 🙇 

`update_all` を使用するように修正した旨把握しました 😄

2018-11-07 07:36 UTC, pokotyamu approved these changes
気になった部分は修正していただけたかと思うので LGTM 🎉 
マージして最後の章に進んでください！

2018-11-08 05:50 UTC, merged