面接日程の申請/承認を通知するメール機能の追加
shoynoi/e-navigator pull request #4
Opened 2018-11-08 06:21 UTC by shoynoi

後半第3章が完了しましたので、レビューよろしくおねがいします。

やりたかったこと
---
- ユーザーが指定した相手に対して面接日程の承認を依頼するメールを送信する機能を追加
- 面接日程が承認された場合、両者に面接日程の確定を知らせるメールを送信する機能を追加

やったこと
----
- ActionMailerを使用してメイラー機能を追加
- development環境にletter opener webを導入
- 日程の承認を依頼する場合に送信するメイラービューを作成し、メールを送信するアクションを追加
- 面接日程が確定した場合に送信するメイラービューを作成し、メールを送信するアクションを追加
- 自身の希望面接日程一覧ページに申請する相手のメールアドレスを表示し、申請するフォームを作成
...

動作確認方法
---
- [ ] ユーザーを2人作成
- [ ] 一方のユーザーをintervieweeとして、新しく希望面接日程を作成
- [ ] もう一方のユーザー(interviewer)のメールアドレスを選択し、申請ボタンを押下
- [ ] 申請が完了しましたとメッセージが表示され、interviewerのメールアドレスに"面接希望日が決まりました"という件名のメールが送信され、intervieweeの希望面接日程一覧ページのリンクが表示される
- [ ] リンクをクリックし、有効な面接日程を承認すると、”面接希望日時を承認しました”とメッセージが表示され、interviewer/interviewee両者に"面接希望日が決まりました"という件名でメールが送信され、メール内で確定した面接日時が表示される

よろしくお願いいたします。:bow:

2018-11-09 02:18 UTC, pokotyamu requested changes
@shoynoi メッソド名の付け方の部分が特に気になりました！ご確認よろしくお願いします！

2018-11-09 02:18 UTC, pokotyamu commented on app/mailers/interview_mailer.rb
> +  def interview_application
`InterviewMailer#interview_application` は `interview` が被っててちょっと冗長な感じがしますね 💭 
また、メソッド名は名詞ではなく、動詞を使う方が一般的ですね！

2018-11-09 02:18 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    InterviewMailer.with(interviewee: @interviewee, interviewer: @interviewer).interview_application.deliver_now
```
InterviewMailer.interview_application(interviewee: @interviewee, interviewer: @interviewer)
```

こんな感じで書くこともできまっせ(一応)

2018-11-09 02:18 UTC, pokotyamu commented on app/views/layouts/application.html.erb
> +              <% end %>
デベロップメントだけ出すの良いですね 👍 
ちゃんと、ルーティング的にも飛べなくしているのも非常にいいと思いました！

2018-11-09 02:18 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @other_users = User.where.not(id: @user)
豆知識

最終的にほしいのは、本人以外の email のリストですよね？
こんな感じにすると中間の User のリストを作るところが省略できて早くなるはずです！

```
@emails = User.where.not(id: @user).pluck(:email)
```

ActiveRecord から特定のカラム抽出は、 `#pluck` 覚えておくと幸せになりますよ〜！
http://railsdoc.com/references/pluck

2018-11-09 02:18 UTC, pokotyamu commented on app/views/interview_mailer/interview_application.html.erb
> +<%= link_to nil, user_interviews_url(@interviewee) %>
[メモ]こんな感じになる。

![image](https://user-images.githubusercontent.com/3479317/48239136-186a5980-e411-11e8-9dfb-583ace71b98b.png)

2018-11-09 13:58 UTC, shoynoi commented on app/mailers/interview_mailer.rb
> +  def interview_application
`InterviewMailer`クラス内で面接日程の申請をする(メールを送信する)という意味で`apply`に変更しました。
また、`InterviewMailer#interview_confirmed`も同様に面接日程を確定する(メールを送信する)となるように`confirm`にリネームしました。

2018-11-09 14:01 UTC, shoynoi commented on app/controllers/interviews_controller.rb
> +    @other_users = User.where.not(id: @user)
確かにそうでした。
お教えいただいた`pluck`を使用するように変更しました。
またそれに伴い、変数名を`others_email`に変更しました。

2018-11-13 01:37 UTC, pokotyamu requested changes
レビュー依頼前に動作確認されましたでしょうか？  😓 
セルフレビューで気づける範囲だと思うので、気をつけてください。
修正お願いします。

2018-11-13 01:37 UTC, pokotyamu commented on app/mailers/interview_mailer.rb
> +  def apply
呼び出し側のメソッド名変え忘れてないですか？ 👀

2018-11-16 00:04 UTC, shoynoi commented
大変失礼いたしました。確認不足でした。
メソッド名とファイル名の変更をし、メールが送信されることを確認いたしました。
お手数おかけして申し訳ありません。

2018-11-16 02:21 UTC, pokotyamu commented
> 大変失礼いたしました。確認不足でした。

自分もたまにやらかすので大丈夫ですよ 🙏 
どんなプルリクエストでも、レビュー出す前のセルフレビューに自分は一番時間を使うようにしてたりしますね(特に動作確認や誤字の確認など。)

2018-11-16 02:22 UTC, pokotyamu commented
メール送れていることを確認しました 👍 
うん良さそう！

2018-11-16 02:22 UTC, pokotyamu approved these changes
LGTM です 👍 
完走お疲れ様でした 🎉  🎉  🎉

2018-11-18 05:33 UTC, merged